### ISSUE TITLE
Change value output

### ISSUE THREAD

**Issue by Alex-Gans** [DanielSan1000/Fenix-Modbus#1]
Good day,

First, thank you for providing your free Modbus Manager!

Is it possible to adjust the value from the Modbus device tag directly? 
I am receiving my temperature value from a Modbus register as 2100. 
Currently, I’m using an internal tag to divide this value by 100 to obtain the actual temperature (21.00°C).

Is there a quicker, real-time conversion method available? Perhaps by using the "Execute After Read" or "Execute Before Write" script function in the Modbus properties section?

Thanks!

**Comment by DanielSan1000** [comment]
Hi

Is very simple you can use VBA and 'x ' the is value before the conversion

Execute After Read -> **x / 10**
Execute Before Write -> **x * 10** // If needed for temperature propobaly not :)

![image](https://github.com/user-attachments/assets/2370d467-9476-4f9a-a8da-37288fdb01df)
